### ISSUE TITLE
Can you add this XL sheet in the README

### ISSUE THREAD

**Issue by fizerkhan** [cheeaun/javascript-error-logging#3]
This XL sheet compares error logging service feature sets

http://goo.gl/wCMHSV

Can you please add it in README.

**Comment by cheeaun** [comment]
@fizerkhan hi, few questions:

- Do you maintain this spreadsheet?
- Is it possible for you to create a PR for this? :wink: 

Thanks.

**Comment by fizerkhan** [comment]
@cheeaun I did not maintain this spreadsheet. It is maintained by @igorsantos07

Yes, i made the pull request #4

**Comment by igorsantos07** [comment]
I usually update it based on comments. It's a sort of PR for Sheets :) 
Any contribution is welcome!
